PACKAGE = display

SOURCE = \
	HMusic.java \
	HMusicWrapper.java \
	HParticle.java \
	MoonParticle.java \
	PlanetParticle.java \
	SolarParticle.java \
	StellaCaeli.java \
	Triangulation.java \
	WanderingParticle.java \
	HMusicController.java

packageclean:
	@rm -f $(TO_ROOT)/$(PACKAGE)/*.class

include $(TO_ROOT)/Makefile